# Training hyperparameters
batch_size: 16
epochs: 10
learning_rate: 0.001
max_seq_len: 32

# Model architecture
embed_dim: 64          # Embedding dimension
num_heads: 4           # Number of attention heads
ff_hidden: 128         # Feedforward hidden size
num_layers: 2          # Number of transformer blocks

# Dataset settings
train_val_split_ratio: 0.1
tokenizer_path: "../data/processed/tokenizer.json"

# Device settings
device: "cuda"         # or "cpu"

# Saving
model_save_path: "../model.pt"